spring:
  datasource:
    url: jdbc:postgresql://yeti-db.cvmqeno83ncx.ap-northeast-2.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret:
    key:
      7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==